// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: src/github.com/kratos2511/go_grpc/primef/primefpb/primef.proto

package primefpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPrimeFactorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *GetPrimeFactorsRequest) Reset() {
	*x = GetPrimeFactorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPrimeFactorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrimeFactorsRequest) ProtoMessage() {}

func (x *GetPrimeFactorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrimeFactorsRequest.ProtoReflect.Descriptor instead.
func (*GetPrimeFactorsRequest) Descriptor() ([]byte, []int) {
	return file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDescGZIP(), []int{0}
}

func (x *GetPrimeFactorsRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetPrimeFactorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Factor int32 `protobuf:"varint,1,opt,name=factor,proto3" json:"factor,omitempty"`
}

func (x *GetPrimeFactorsResponse) Reset() {
	*x = GetPrimeFactorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPrimeFactorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrimeFactorsResponse) ProtoMessage() {}

func (x *GetPrimeFactorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrimeFactorsResponse.ProtoReflect.Descriptor instead.
func (*GetPrimeFactorsResponse) Descriptor() ([]byte, []int) {
	return file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDescGZIP(), []int{1}
}

func (x *GetPrimeFactorsResponse) GetFactor() int32 {
	if x != nil {
		return x.Factor
	}
	return 0
}

var File_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto protoreflect.FileDescriptor

var file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDesc = []byte{
	0x0a, 0x3e, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x32, 0x35, 0x31, 0x31, 0x2f, 0x67, 0x6f, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x66, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65,
	0x66, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x66, 0x70, 0x62, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x31, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x32,
	0x70, 0x0a, 0x12, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x6d,
	0x65, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65,
	0x66, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x69,
	0x6d, 0x65, 0x66, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x46, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x33, 0x5a, 0x31, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x32, 0x35, 0x31, 0x31, 0x2f, 0x67,
	0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x66, 0x2f, 0x70, 0x72,
	0x69, 0x6d, 0x65, 0x66, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDescOnce sync.Once
	file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDescData = file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDesc
)

func file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDescGZIP() []byte {
	file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDescOnce.Do(func() {
		file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDescData)
	})
	return file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDescData
}

var file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_goTypes = []interface{}{
	(*GetPrimeFactorsRequest)(nil),  // 0: primefpb.GetPrimeFactorsRequest
	(*GetPrimeFactorsResponse)(nil), // 1: primefpb.GetPrimeFactorsResponse
}
var file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_depIdxs = []int32{
	0, // 0: primefpb.PrimeFactorService.GetPrimeFactors:input_type -> primefpb.GetPrimeFactorsRequest
	1, // 1: primefpb.PrimeFactorService.GetPrimeFactors:output_type -> primefpb.GetPrimeFactorsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_init() }
func file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_init() {
	if File_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPrimeFactorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPrimeFactorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_goTypes,
		DependencyIndexes: file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_depIdxs,
		MessageInfos:      file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_msgTypes,
	}.Build()
	File_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto = out.File
	file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_rawDesc = nil
	file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_goTypes = nil
	file_src_github_com_kratos2511_go_grpc_primef_primefpb_primef_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrimeFactorServiceClient is the client API for PrimeFactorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrimeFactorServiceClient interface {
	GetPrimeFactors(ctx context.Context, in *GetPrimeFactorsRequest, opts ...grpc.CallOption) (PrimeFactorService_GetPrimeFactorsClient, error)
}

type primeFactorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeFactorServiceClient(cc grpc.ClientConnInterface) PrimeFactorServiceClient {
	return &primeFactorServiceClient{cc}
}

func (c *primeFactorServiceClient) GetPrimeFactors(ctx context.Context, in *GetPrimeFactorsRequest, opts ...grpc.CallOption) (PrimeFactorService_GetPrimeFactorsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrimeFactorService_serviceDesc.Streams[0], "/primefpb.PrimeFactorService/GetPrimeFactors", opts...)
	if err != nil {
		return nil, err
	}
	x := &primeFactorServiceGetPrimeFactorsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrimeFactorService_GetPrimeFactorsClient interface {
	Recv() (*GetPrimeFactorsResponse, error)
	grpc.ClientStream
}

type primeFactorServiceGetPrimeFactorsClient struct {
	grpc.ClientStream
}

func (x *primeFactorServiceGetPrimeFactorsClient) Recv() (*GetPrimeFactorsResponse, error) {
	m := new(GetPrimeFactorsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrimeFactorServiceServer is the server API for PrimeFactorService service.
type PrimeFactorServiceServer interface {
	GetPrimeFactors(*GetPrimeFactorsRequest, PrimeFactorService_GetPrimeFactorsServer) error
}

// UnimplementedPrimeFactorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrimeFactorServiceServer struct {
}

func (*UnimplementedPrimeFactorServiceServer) GetPrimeFactors(*GetPrimeFactorsRequest, PrimeFactorService_GetPrimeFactorsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPrimeFactors not implemented")
}

func RegisterPrimeFactorServiceServer(s *grpc.Server, srv PrimeFactorServiceServer) {
	s.RegisterService(&_PrimeFactorService_serviceDesc, srv)
}

func _PrimeFactorService_GetPrimeFactors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPrimeFactorsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrimeFactorServiceServer).GetPrimeFactors(m, &primeFactorServiceGetPrimeFactorsServer{stream})
}

type PrimeFactorService_GetPrimeFactorsServer interface {
	Send(*GetPrimeFactorsResponse) error
	grpc.ServerStream
}

type primeFactorServiceGetPrimeFactorsServer struct {
	grpc.ServerStream
}

func (x *primeFactorServiceGetPrimeFactorsServer) Send(m *GetPrimeFactorsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrimeFactorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "primefpb.PrimeFactorService",
	HandlerType: (*PrimeFactorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPrimeFactors",
			Handler:       _PrimeFactorService_GetPrimeFactors_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/github.com/kratos2511/go_grpc/primef/primefpb/primef.proto",
}
