// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: src/github.com/kratos2511/go_grpc/calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Numbers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numbers []int32 `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
}

func (x *Numbers) Reset() {
	*x = Numbers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Numbers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Numbers) ProtoMessage() {}

func (x *Numbers) ProtoReflect() protoreflect.Message {
	mi := &file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Numbers.ProtoReflect.Descriptor instead.
func (*Numbers) Descriptor() ([]byte, []int) {
	return file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *Numbers) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

type CalculateSumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Numbers *Numbers `protobuf:"bytes,1,opt,name=numbers,proto3" json:"numbers,omitempty"`
}

func (x *CalculateSumRequest) Reset() {
	*x = CalculateSumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateSumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateSumRequest) ProtoMessage() {}

func (x *CalculateSumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateSumRequest.ProtoReflect.Descriptor instead.
func (*CalculateSumRequest) Descriptor() ([]byte, []int) {
	return file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateSumRequest) GetNumbers() *Numbers {
	if x != nil {
		return x.Numbers
	}
	return nil
}

type CalculateSumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sum int32 `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *CalculateSumResponse) Reset() {
	*x = CalculateSumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculateSumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateSumResponse) ProtoMessage() {}

func (x *CalculateSumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateSumResponse.ProtoReflect.Descriptor instead.
func (*CalculateSumResponse) Descriptor() ([]byte, []int) {
	return file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateSumResponse) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto protoreflect.FileDescriptor

var file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDesc = []byte{
	0x0a, 0x4a, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x32, 0x35, 0x31, 0x31, 0x2f, 0x67, 0x6f, 0x5f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x23, 0x0a, 0x07, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x44, 0x0a,
	0x13, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x22, 0x28, 0x0a, 0x14, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x53, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x32, 0x6a, 0x0a,
	0x13, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x75, 0x6d, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x53, 0x75, 0x6d, 0x12, 0x1f, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x75, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x75, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x73, 0x72, 0x63,
	0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x72, 0x61, 0x74,
	0x6f, 0x73, 0x32, 0x35, 0x31, 0x31, 0x2f, 0x67, 0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDescOnce sync.Once
	file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDescData = file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDesc
)

func file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDescGZIP() []byte {
	file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDescOnce.Do(func() {
		file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDescData)
	})
	return file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDescData
}

var file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_goTypes = []interface{}{
	(*Numbers)(nil),              // 0: calculator.Numbers
	(*CalculateSumRequest)(nil),  // 1: calculator.CalculateSumRequest
	(*CalculateSumResponse)(nil), // 2: calculator.CalculateSumResponse
}
var file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.CalculateSumRequest.numbers:type_name -> calculator.Numbers
	1, // 1: calculator.CalculateSumService.calculateSum:input_type -> calculator.CalculateSumRequest
	2, // 2: calculator.CalculateSumService.calculateSum:output_type -> calculator.CalculateSumResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_init() }
func file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_init() {
	if File_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Numbers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateSumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculateSumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_goTypes,
		DependencyIndexes: file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_depIdxs,
		MessageInfos:      file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_msgTypes,
	}.Build()
	File_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto = out.File
	file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_rawDesc = nil
	file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_goTypes = nil
	file_src_github_com_kratos2511_go_grpc_calculator_calculatorpb_calculator_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculateSumServiceClient is the client API for CalculateSumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculateSumServiceClient interface {
	CalculateSum(ctx context.Context, in *CalculateSumRequest, opts ...grpc.CallOption) (*CalculateSumResponse, error)
}

type calculateSumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculateSumServiceClient(cc grpc.ClientConnInterface) CalculateSumServiceClient {
	return &calculateSumServiceClient{cc}
}

func (c *calculateSumServiceClient) CalculateSum(ctx context.Context, in *CalculateSumRequest, opts ...grpc.CallOption) (*CalculateSumResponse, error) {
	out := new(CalculateSumResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculateSumService/calculateSum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculateSumServiceServer is the server API for CalculateSumService service.
type CalculateSumServiceServer interface {
	CalculateSum(context.Context, *CalculateSumRequest) (*CalculateSumResponse, error)
}

// UnimplementedCalculateSumServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculateSumServiceServer struct {
}

func (*UnimplementedCalculateSumServiceServer) CalculateSum(context.Context, *CalculateSumRequest) (*CalculateSumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateSum not implemented")
}

func RegisterCalculateSumServiceServer(s *grpc.Server, srv CalculateSumServiceServer) {
	s.RegisterService(&_CalculateSumService_serviceDesc, srv)
}

func _CalculateSumService_CalculateSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateSumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculateSumServiceServer).CalculateSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculateSumService/CalculateSum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculateSumServiceServer).CalculateSum(ctx, req.(*CalculateSumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculateSumService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculateSumService",
	HandlerType: (*CalculateSumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "calculateSum",
			Handler:    _CalculateSumService_CalculateSum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/github.com/kratos2511/go_grpc/calculator/calculatorpb/calculator.proto",
}
